fail_fast: true
default_install_hook_types: [pre-commit]
default_stages: [pre-commit]
repos:
    - repo: https://github.com/crate-ci/typos
      rev: v1.28.1
      hooks:
          - id: typos
    - repo: local
      hooks:
          - id: fmt
            name: fmt
            language: system
            types: [file, rust]
            entry: make format
            pass_filenames: false

          - id: clippy
            name: clippy
            language: system
            types: [file, rust]
            entry: make lint
            pass_filenames: false

          - id: unit tests
            name: unit tests
            language: system
            types: [file, rust]
            entry: make utest
            pass_filenames: false
