# Testing CI - Runs on each PR and Push

name: Test
on:
    pull_request:
    push:
        branches:
            - main

permissions:
    id-token: write
    contents: read
env:
    CARGO_TERM_COLOR: always
    RUST_TOOLCHAIN: 1.85.0
    RUST_COMPONENTS: "rust-std"
jobs:
    # cargo fmt check
    check-formatting:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install Rust Toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: ${{ env.RUST_TOOLCHAIN }}
                  default: true
                  components: rustfmt

            - name: Check formatting
              run: cargo fmt --check

    # clippy
    check-clippy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install Rust Toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: ${{ env.RUST_TOOLCHAIN }}
                  default: true
                  components: clippy

            - name: Clippy Check
              run: cargo clippy --all

    # Rust unit, doc and integration
    test-rust:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install Rust Toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: ${{ env.RUST_TOOLCHAIN }}
                  default: true

            - name: Run rust tests
              env:
                ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
              run: cargo test
